trigger:
  batch: true
  branches:
    include:
    - main
    - develop


variables:
  buildConfiguration: 'Release'

pool: 
  name: Default

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.x'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/Donace-BE-Project.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/Donace-BE-Project.csproj'


- task: DotNetCoreCLI@2
  inputs:
    command: publish
    projects: '**/Donace-BE-Project.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    publishWebProjects: True
    zipAfterPublish: True

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'drop'
    publishLocation: 'pipeline'